### ISSUE TITLE
ApolloCodegenLib/IR+EntitySelectionTree.swift:192: Fatal error

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2434]
I've copied this over from https://github.com/apollographql/iOSCodegenTemplate/issues/21#issue-1336030377

> Good morning,
I'm trying to see if I can get the new Swift Code gen to work with our work project and I think its generating most of our files properly but the codegen keeps on erroring out with:
> ```
> ApolloCodegenLib/IR+EntitySelectionTree.swift:192: Fatal error
> ```
> For now I'm assuming user error since I probably dont have the configuration set up correctly but based on that fatal error is there anything obvious that I'm doing wrong?

**Comment by calvincestari** [comment]
@iAmericanBoy if there is anything sensitive in that debug output you'd rather not share take a look at the relevant part of the schema it's referencing. It would be helpful to see whether we can replicate this error outside of your schema by duplicating the type/interface/union/etc. that's being referenced.

**Comment by iAmericanBoy** [comment]
is there away to enable a verbose mode on the script? the only message I see is the one I had posted in the first comment.

**Comment by calvincestari** [comment]
I meant you have to break on the error line and manually print out the two parameters. We need to change the error line to include those details.

**Comment by iAmericanBoy** [comment]
I was able to print out the child and its a 2000 line object. Should I be looking for something specific that would point you into the right direction? The query that is causing the crash has implementations and fragments in it if that helps

**Comment by calvincestari** [comment]
Is the child object the query itself? I suspect it's not but rather one of the fragments or such. Once you've narrowed down to which part within the query is causing the problem trying to replicate that in a separate schema we can use would be great.

If not then maybe we can hop on to a Zoom call in the next few days and debug together; I'm in GMT +2 time zone for the next couple weeks so early in your work day (assuming you're in Chicago, GMT -5) would be best.

**Comment by iAmericanBoy** [comment]
I started with removing the query that was causing the issue but we had lots of other queries failing with that same line of code so I stopped deleting them for now after deleting ~20 queries. I'm thinking either our schema/query isn't compatible in some way or maybe the setup is wrong? Im happy to jump on a zoom this week I'm in Michigan so UTC -4. My morning s are fee just let me know what day works best. Here is my current generate function from main.swift
```swift
  /// The sub-command to actually generate code.
  struct GenerateCode: ParsableCommand {
    static var configuration = CommandConfiguration(
      commandName: "generate",
      abstract: "Generates swift code from your schema + your operations based on information set up in the `GenerateCode` command.")

    func run() throws {
      // TODO: Replace the placeholder here with the name of the folder containing your project's code files.
      /// The root of the target for which you want to generate code.
      let targetRootURL = SourceRootURL
        .apollo.childFolderURL(folderName: "Apollo")

      // TODO: Replace the placeholder here with the name you would like to give your schema.
      /// The name of the module that will contain your generated schema objects.
      let generatedSchemaModuleName: String = "M1Core"

      /// The URL where the generated schema files will be written to.
      let schemaModuleURL = SourceRootURL
            .apollo.childFolderURL(folderName: "M1Core")
            .apollo.childFolderURL(folderName: "Apollo")
            .apollo.childFolderURL(folderName: "Generated")

      // Make sure the folders exists before trying to generate code.
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: targetRootURL.path)
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: schemaModuleURL.path)

      // Create the Codegen configuration object. For all configuration parameters see: https://www.apollographql.com/docs/ios/api/ApolloCodegenLib/structs/ApolloCodegenConfiguration/
      let codegenConfiguration = ApolloCodegenConfiguration(
        schemaName: generatedSchemaModuleName,
        input: ApolloCodegenConfiguration.FileInput(schemaPath: SchemaOutputURL.path,operationSearchPaths: [SourceRootURL.appendingPathComponent("M1Core/Apollo**/*.graphql").path]),
        output: ApolloCodegenConfiguration.FileOutput(
          schemaTypes: ApolloCodegenConfiguration.SchemaTypesFileOutput(
            path: schemaModuleURL.path,
            moduleType: .embeddedInTarget(name: generatedSchemaModuleName))
        )
      )

      // Actually attempt to generate code.
      try ApolloCodegen.build(with: codegenConfiguration)
    }
  }
```

**Comment by calvincestari** [comment]
> I'm thinking either our schema/query isn't compatible in some way or maybe the setup is wrong?

As long as the schema is spec-compliant our code generator needs to work with it. The new code generator is a complete rewrite in Swift so it's possible there are bugs.

There doesn't appear to be anything obviously wrong with the configuration:
* It looks like you might missing a `/` in operationSearchPaths between `Apollo` and `**`.
* You're not overriding the default for `OperationsFileOutput` so the generated operation files will be co-located with the original `.graphql` files.
* You're not overriding the defaults for `OutputOptions` but none of those should be causing the IR build to fail.

**Comment by calvincestari** [comment]
I assume you're trying with `1.0.0-beta.1`, if so could you try with the latest from `release/1.0` and see if the same problem persists. `beta.2` is nearing release and there have been quite a few changes since `beta.1`.

**Comment by iAmericanBoy** [comment]
I haven't been able to try this with the beta 2 branch yet. Our schema is public so I can share it with you would just prefer not to publish it on GitHub. But also happy to jump on a zoom whit you all.

**Comment by AnthonyMDev** [comment]
If you can e-mail your schema and at least one failing operation to me at anthony@apollographql.com, I will be happy to resolve this bug for you!

**Comment by iAmericanBoy** [comment]
Email has been send thank you!

**Comment by AnthonyMDev** [comment]
Working on this now! Thanks for sending it all over.

**Comment by AnthonyMDev** [comment]
FYI @iAmericanBoy, we removed the Apollo URL helpers in the most recent beta version, so you'll need to alter your code generation swift script to handle the URL resolving yourself.

But with Beta 2.0, we have a codegen CLI that we actually recommend as an easier way to configure codegen for most use cases!

**Comment by AnthonyMDev** [comment]
@iAmericanBoy, okay, I've ran the codegen with your example schema and operations. It ran just fine and generated all the files.

What version of Apollo were you using? I imagine (due to the use of removed APIs in your `main.swift` file, that you were using the Beta 1 version. We released Beta 2 yesterday. Can you try updating to Beta 2 and let me know if you are still seeing this issue in your project? I think we probably fixed it already!

**Comment by iAmericanBoy** [comment]
> @iAmericanBoy, okay, I've ran the codegen with your example schema and operations. It ran just fine and generated all the files.
Oh wow thats music to my ears. I didn't realize beta 2 was released. I will have to try that version as I was only ever using beta 1. I will report back by EOW once I get beta 2 working.

**Comment by iAmericanBoy** [comment]
> But with Beta 2.0, we have a codegen CLI that we actually recommend as an easier way to configure codegen for most use cases!
Im sorry I don think I understand. how is the Codegen CLI different then the swift Scrip I was using?

**Comment by iAmericanBoy** [comment]
@AnthonyMDev sadly still seeing the same issue on beta2 which makes me believe its user error since it worked on your machine.

**Comment by AnthonyMDev** [comment]
Hmmm. So odd, I'll need to look at your setup since I can't reproduce it. Let's set up a Zoom call. I'll e-mail you!

**Comment by AnthonyMDev** [comment]
Fixed it! It's PR https://github.com/apollographql/apollo-ios/pull/2452. We'll pull it in Monday morning and you can keep moving forward pointing to the `release/1.0` branch!

**Comment by AnthonyMDev** [comment]
PR's been merged into the release branch
