### ISSUE TITLE
Incorrect handling of types that start lower-case

### ISSUE THREAD

**Issue by Almaz5200** [apollographql/apollo-ios#2460]
## Bug report

**This is v1.0.0 beta issue**
If there is type in schema that starts with lower-case letter, then type file will generate making it uppercase, but the operations will try to use it with lower case

<img width="1133" alt="Screenshot 2022-08-24 at 21 19 53" src="https://user-images.githubusercontent.com/21291840/186483745-18090507-11ab-4a1f-9387-926330f048c8.png">
<img width="497" alt="Screenshot 2022-08-24 at 21 23 40" src="https://user-images.githubusercontent.com/21291840/186483810-948ac576-21fe-4d77-bde8-c754180b16cb.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0-beta.2
- Xcode version: 13.4.1
- Swift version: 5.6
- Package manager: SPM

## Steps to reproduce

Generate code with schema that contains lower-case starting types

**Comment by AnthonyMDev** [comment]
Thank you! looks like we missed that there. I'll have a fix in the `release/1.0` branch for this ASAP!

**Comment by AnthonyMDev** [comment]
This is fixed in https://github.com/apollographql/apollo-ios/pull/2462! Once that's merged in, you'll be able to pull the `release/1.0` branch and all should be well. Thanks for the bug report!

**Comment by AnthonyMDev** [comment]
Okay merges! Closing this issue

**Comment by Almaz5200** [comment]
Thank you!

<img width="334" alt="Screenshot 2022-08-25 at 17 43 33" src="https://user-images.githubusercontent.com/21291840/186681053-eba574cb-85d6-4f0b-8d86-cfa71e884e37.png">

There's still an issue with that. Typename for lowercase type names is generated uppercased too, so they don't match an actual typename when parsing

**Comment by Almaz5200** [comment]
I believe the issue is on ObjectTemplate.swift file on line 17 (at least part of the issue)

**Comment by Almaz5200** [comment]
And in SchemaMetadataTemplate.swift as well :)

**Comment by Almaz5200** [comment]
Actually I've fixed that in #2465
