### ISSUE TITLE
Version mismatch when using apollo-cli-install for v1.1.1

### ISSUE THREAD

**Issue by matthewspear** [apollographql/apollo-ios#2946]
### Summary

I've updated my packages and the sidebar of Xcode shows `Apollo 1.1.1`.

Running:
`swift package --allow-writing-to-package-directory apollo-cli-install`

Then checking the version of the generated alias still shows `1.0.5`.

So I download the correct CLI via the Release tab, run generate and get the mis-match message:
```
Error: Error: Apollo Version Mismatch
We've detected that the version of the Apollo Codegen CLI does not match the version of the
Apollo library used in your project. This may lead to incompatible generated objects.

Please update your version of the Codegen CLI by following the instructions at:
https://www.apollographql.com/docs/ios/code-generation/codegen-cli/#installation

CLI version: 1.1.1
Apollo version: 1.0.5

To ignore this error during code generation, use the argument: --ignore-version-mismatch.
```

I'm running on Xcode 14.2.0.

No major issue for me, but it seems that the CLI isn't picking up my newer version of the package – Is this expected behavior?

For anyone running into this issue, download the cli via releases and use the --ignore-version-mismatch. Just thought it'd be worth reporting incase someone else stumbles upon it / a possible regression.

### Version

1.1.1

### Steps to reproduce the behavior

- Update package to `1.1.1`
- Run `swift package --allow-writing-to-package-directory apollo-cli-install`
- Check version of CLI `./apollo-ios-cli --version`

Expected behavior:
- returned `1.1.1`

Received behavior:
- returned `1.0.5`

**Comment by calvincestari** [comment]
Hi @matthewspear, thanks for reporting your issue.

> No major issue for me, but it seems that the CLI isn't picking up my newer version of the package – Is this expected behavior?

No, that would be a bug. It should certainly be able to compare the two versions correctly.

I cannot reproduce the behaviour you describe though. I've followed along with your steps, built the binary, verified versions, initialized and generated source code but it all works as expected. I also verified the versions of the uploaded CLI binaries and everything seems to match up.

If you're able to replicate this behaviour in a standalone project you can share then we can certainly help further. I'll leave this issue open for now to see if you can share any further details to help track down the potential bug.

**Comment by matthewspear** [comment]
Thanks Calvin, appreciate you looking into it...

I've just tried to replicate from a new project / same package setup and I get the expected behaviour, v1.1.1 is resolved from package file and v1.1.1 is install from the cli install command.

My only guess is my main project has some stale state when the cli install command is called it pulls / build from a previous set of files.

I'll try purging / clean building the full project and see if that makes any difference!

**Comment by calvincestari** [comment]
@matthewspear I'm going to close this issue. If this continues to be a persistent issue comment back here and we can pick it up again.

**Comment by wmurmann** [comment]
I ran into this. Open up your xcodeproj folder in a file editor. Checkout project.xcworkspace/xcshareddata/swiftpm/Package.resolved. There should be a stale resolved package pin in there.

I was working in my workspace so I never opened up the xcodeproj app. If you open that up it Xcode will resolve the new package and clear out the stale pin. Then just switch back to your workspace and you should be good to go.

**Comment by calvincestari** [comment]
Thanks for sharing your findings @wmurmann. It really depends how the dependency was added to your project which can be done through SPM (Package.swift file) or Xcode (still SPM but managed by Xcode). The version checker has an [order of priority](https://github.com/apollographql/apollo-ios/blob/df4648bb3e83c8509f74aa76f34b023c61ab81cf/Sources/CodegenCLI/Extensions/VersionChecker.swift#L26) in which it validates the possible dependencies locations.

**Comment by mayank070188** [comment]
This issue still exists? When I update my Apollo SPM package to the latest one CLI gets old? Why it didn't updated by itself. Moreover there is no direct way to update my CLI client.

<img width="907" alt="Screenshot 2024-06-05 at 17 50 51" src="https://github.com/apollographql/apollo-ios/assets/783853/92242781-b42b-43d5-be03-e77b64a9114d">

<img width="539" alt="Screenshot 2024-06-05 at 17 49 18" src="https://github.com/apollographql/apollo-ios/assets/783853/a6b225f9-a21b-4d35-9d0b-e6377414f5f4">

**Comment by calvincestari** [comment]
Hi @mayank070188 

> When I update my Apollo SPM package to the latest one CLI gets old? Why it didn't updated by itself.

The CLI update is not automatic when your dependencies are updated. The version check in the CLI exists to alert you to this mismatch and you will need to manually update the CLI.

> Moreover there is no direct way to update my CLI client.

Yes there is, it's in the Xcode project menu. [Here is a screenshot](https://github.com/apollographql/apollo-ios/assets/146856/1b723805-6074-446a-8788-e3d97d182b31) showing you where to find it.

**Comment by mayank070188** [comment]
Even I added the Screenshot! It is either not present for everyone or there is some bug which makes it not available for everyone. I had to delete the Apollo lib and reinstall with higher version to fix the issue.

**Comment by calvincestari** [comment]
> Even I added the Screenshot! It is either not present for everyone or there is some bug which makes it not available for everyone. 

That's because it's not in the 'Packages' menu, as your screenshot shows. Right click on your project in the Project Navigator (first tab of the Navigator pane) and it will be there.
