### ISSUE TITLE
Cache records only storing interface fields

### ISSUE THREAD

**Issue by Mordil** [apollographql/apollo-ios#3195]
### Summary

I have a unit test that loads a query from the cache to assert there's no cached data, then executes the same query with a mocked JSON response, then tries to load the cached response.

Prior to 1.x this test passed, now in 1.3.3 the test is failing. The resolved GraphQL representation is only storing the interface fields, rather than any of the polymorphic fields.

```graphql
query DefaultPaymentProcessor {
 currentAccount {
  defaultPaymentProcessor {
     ... on PaymentProcessorStripeConnect {
      __typename
      publishableKey
      accountId
      type
    }
    ... on PaymentProcessorStripeIntents {
      __typename
      publishableKey
      possibleAccountId: accountId
      type
    }
    ... on PaymentProcessorStripeCustomConnect {
      __typename
      publishableKey
      type
    }
    ... on PaymentProcessorStripe {
      __typename
      publishableKey
      type
    }
  }
}
}
```

```swift
// Response object
static var response: JSONObject {
    [
      "data": [
        "currentAccount": [
          "__typename": "Account",
          "defaultPaymentProcessor": [
            "__typename": "PaymentProcessorStripe",
            "publishableKey": "pk_test_Z9OxMdgs7XIhB5NzeDSjXV6o",
            "type": "STRIPE"
          ] as JSONObject
        ] as JSONObject
      ] as JSONObject
    ]
  }
```

```swift
// unit test

  func testDefaultPaymentProcessorSyncJobFetchData() async throws {
    let bodyObject = MockDefaultPaymentProcessorQuery.response
    let cache = InMemoryNormalizedCache()
    let store: ApolloStore = .init(cache: cache)
    // this uses the DefaultInterceptorProvider
    let mockNetworkTransport = Socrates.MockNetworkTransport(body: bodyObject, store: store)
    let client: ApolloClient = .init(networkTransport: mockNetworkTransport, store: store)
    let query = DefaultPaymentProcessorQuery()
    let job = DefaultPaymentProcessorSyncJob()

    await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) -> Void in
      client.store.load(query) { result in
        defer { continuation.resume() }
        if case .success = result {
          XCTFail("Cache result must not exist for this query")
        }
      }
    }
    try await job.run(using: client)
    let defaultProcessor = try await withCheckedThrowingContinuation {
      (continuation: CheckedContinuation<DefaultPaymentProcessor?, Error>) -> Void in

      client.store.load(query) { result in
        do {
          let processor = try result.get().data?.currentAccount?.defaultPaymentProcessor
          continuation.resume(returning: processor)
        } catch {
          continuation.resume(throwing: error)
        }
      }
    }

    XCTAssertNil(defaultProcessor?.asPaymentProcessorStripeIntents)
    // response is Stripe
    XCTAssertNotNil(defaultProcessor?.asPaymentProcessorStripe)
       ^^^^^^^^ value is nil! only the '__typename' is stored in the data dict!
```

### Version

1.3.3

### Steps to reproduce the behavior

I'm not sure what exactly is causing it.

It seems to be isolated to our code.

Attached is the generated GraphQL operation file.

[DefaultPaymentProcessorQuery.txt](https://github.com/apollographql/apollo-ios/files/12354435/DefaultPaymentProcessorQuery.txt)

### Anything else?

Even when running with SQLite as the normalized cache, the JSON being stored is only the interface

![Screenshot 2023-08-15 at 21 33 39](https://github.com/apollographql/apollo-ios/assets/3506776/e0c4b87b-ba98-4110-8872-10f8365d1912)

The `Socrates.MockNetworkTransport` type is almost a carbon copy of the internal one in Apollo

Here's the implementation

```swift
public init(
    body: JSONObject,
    isReturningError: Bool = false,
    store: ApolloStore = .init(cache: InMemoryNormalizedCache()),
    responseProvider: @escaping (URLRequest) -> Data? = { _ in nil }
  ) {
    let testURL = kMockServerURL

    self.mockClient = MockURLSessionClient(responseProvider: responseProvider)
    self.mockClient.isReturningError = isReturningError
    self.mockClient.data = try! JSONSerializationFormat.serialize(value: body)
    self.mockClient.response = HTTPURLResponse(
      url: testURL,
      statusCode: 200,
      httpVersion: nil,
      headerFields: nil)

    super.init(
      interceptorProvider: DefaultInterceptorProvider(
        client: self.mockClient,
        store: store
      ),
      endpointURL: testURL
    )
  }
```

**Comment by AnthonyMDev** [comment]
Thank you for providing so much information in this bug report. Everything looks like it should be working... so I am equally at a loss as to what is happening here right now. I'm feeling that is has to be a very specific edge case, because if this functionality wasn't working properly on a broad scope, A) our unit tests would catch it, B) a lot of other people would be filing bug reports.

I'm going to see if I can reproduce this on my machine with the attached generated query and try to debug it.

**Comment by AnthonyMDev** [comment]
@Mordil I am not able to reproduce this issue by just using the generated model and response data you've provided. There must be something else going on with your project that is causing this to happen.

Is there a chance you would be able to put together a reproduction case in a sample project you could provide to me? I really need to be able to reproduce this and attach the debugger to figure out what is causing the data to not be written to the cache.

**Comment by AnthonyMDev** [comment]
Hi @Mordil, wanted to follow up on this one. I was unable to reproduce, can you help provide me more information here so we can verify this is a bug? Thanks!

**Comment by Mordil** [comment]
@AnthonyMDev I haven't had time to invest in a smaller reproduction case, and I honestly wanted to update our fork to 1.5 to see if https://github.com/apollographql/apollo-ios/issues/3092 fixed this issue, because it sounds kinda familiar to this one

Sorry for being dark on it, our priorities at work shifted away from Apollo and I'm just now getting back to it this week

**Comment by Mordil** [comment]
I still haven't had time to produce a small reproduction project, but I did update our fork to v1.5 and this issue still reproduces for us which is a data point I guess

**Comment by Mordil** [comment]
I finally got around to extracting the test cases that fail for us (there's now 2) into a small project, but when I ran the tests the passed! So I'm dumbfounded.

They even pass when pointed to our fork, so it's not an issue with code in our fork.

But I have no idea what's different between the reproduction project and ours, I literally copied 100% (aside from import statements) our test code + queries + generated schema files until things started to compile

[apollo-3195.zip](https://github.com/apollographql/apollo-ios/files/13243400/apollo-3195.zip)

**Comment by Mordil** [comment]
Our code keeps failing when we try to access types with their polymorphic accessors `asXYZ` in the `_asInlineFragment()` check to see if it fulfills all the fragments.

It has a reference to fulfill the baseline type fragment, but not the more concrete version, even though the `__typename` is the more concrete type

![Screenshot 2023-11-02 at 14 00 59](https://github.com/apollographql/apollo-ios/assets/3506776/ae4c76c6-f730-4ca4-8c7e-8f95b48ef456)

**Comment by Mordil** [comment]
👀 What I think is wrong is the `__objectType` is returning `nil`.

In the reproduction case, where I re-generated all the schema code, the `objectType(forTypename:)` method appropriately has a _giant_ list of object lookups, but in our actual project that method is _tiny_.

Even when re-running the codegen through the `ApolloCodegenLib` in our custom Swift CLI app.

After manually adding entries for the object references, everything works as expected.

So the root issue is our `SchemaMetadata.swift` file is _not_ being updated in our codegen command...

**Comment by Mordil** [comment]
So we're running into the issue where our desired architecture isn't supported by the codegen for this particular file because it's the "last one wins" for writing the `SchemaMetadata.swift` file.

We have an "umbrella" package, that is broken into separate submodules that have different domain purposes (they call different GraphQL queries & mutations, working on different schema objects).

```sh
umbrella-package
  - shared-core # contains SchemaMetadata.swift, all the Objects, Interfaces, etc
  - module-a # contains all the Operations ModuleA cares about
  - module-b # contains all the Operations ModuleB cares about
```

Everything works if **Oracle** is the last module to be processed, but I assume that's until the day **Registrar** or **Patron** has code that **Oracle** doesn't know about, in which case we have a Catch-22 on the order of codegen.

How can we get our desired codegen architecture, while making sure that `SchemaMetadata.swift` is properly codegen?

<details>
<summary>
We use the following code for using <b>ApolloCodegenLib</b>
</summary>

```swift
    for projectSubdirectory in ["AcropolisCore", "Merchant", "Oracle", "Patron", "Registrar"] {
      self.runApollo(
        moduleName: projectSubdirectory,
        schemaNamespace: "AcropolisCore",
        testSupportRelativePath: "Acropolis/\(projectSubdirectory)",
        schemaOutputDirectory: .acropolisDirectoryURL
          .appending(components: "AcropolisCore", "Sources", "GraphQL", "Schema"),
        operationsOutputOptions: .relative(
          subpath: "../Sources/GraphQL/Operations",
          accessModifier: .public
        ),
        rootURL: .acropolisDirectoryURL
      )
    }

  private func runApollo(
    moduleName: String,
    schemaNamespace: String,
    testSupportRelativePath: String,
    schemaOutputDirectory: URL,
    operationsOutputOptions: ApolloCodegenConfiguration.OperationsFileOutput,
    rootURL: URL
  ) {
      try ApolloCodegen.build(
        with: .init(
          schemaName: schemaNamespace,
          input: .init(
            schemaPath: URL.graphQLSchemaURL.path
          ),
          output: .init(
            schemaTypes: .init(
              path: schemaOutputDirectory.path,
              moduleType: .other
            ),
            operations: operationsOutputOptions,
            testMocks: .absolute(
              path: URL.projectRootURL
                .appending(components: testSupportRelativePath, "TestSupport", "Mocks")
                .relativePath,
              accessModifier: .public
            )
          ),
          options: .init(
            deprecatedEnumCases: .include,
            schemaDocumentation: .include,
            selectionSetInitializers: .all,
            operationDocumentFormat: .definition,
            warningsOnDeprecatedUsage: .include,
            conversionStrategies: .init(enumCases: .camelCase),
            markOperationDefinitionsAsFinal: true
          ),
          schemaDownloadConfiguration: .none // we always use the schema file stored in git
        ),
        withRootURL: rootURL.appendingPathComponent(moduleName)
      )
  }
```
</details>

**Comment by AnthonyMDev** [comment]
Hey @Mordil. Thanks for all of this additional information!

The way you are using the codegen engine is not currently supported. In order to properly create the schema module and the `SchemaMetadata.swift` file, all of your operations need to be run through the code generation engine in the same process. Otherwise you will get exactly the issue you are dealing with here (`SchemaMetadata` and Schema module files possibly being incorrect or missing).

But you can still use the codegen engine to generate get this to work nearly the same at what you've got right now.

Try something like this:
```swift
    self.runApollo(
      schemaNamespace: "AcropolisCore",
      schemaOutputDirectory: .acropolisDirectoryURL
        .appending(components: "AcropolisCore", "Sources", "GraphQL", "Schema"),
      operationsOutputOptions: .relative(
        subpath: "../Sources/GraphQL/Operations",
        accessModifier: .public
      ),
      rootURL: .acropolisDirectoryURL
    )

  private func runApollo(
    schemaNamespace: String,
    schemaOutputDirectory: URL,
    operationsOutputOptions: ApolloCodegenConfiguration.OperationsFileOutput,
    rootURL: URL
  ) {
      try ApolloCodegen.build(
        with: .init(
          schemaName: schemaNamespace,
          input: .init(
            schemaPath: URL.graphQLSchemaURL.path
          ),
          output: .init(
            schemaTypes: .init(
              path: schemaOutputDirectory.path,
              moduleType: .other
            ),
            operations: operationsOutputOptions,
            testMocks: .absolute(
              path: URL.projectRootURL
                .appending(components: "TestSupport", "Mocks")
                .relativePath,
              accessModifier: .public
            )
          ),
          options: .init(
            deprecatedEnumCases: .include,
            schemaDocumentation: .include,
            selectionSetInitializers: .all,
            operationDocumentFormat: .definition,
            warningsOnDeprecatedUsage: .include,
            conversionStrategies: .init(enumCases: .camelCase),
            markOperationDefinitionsAsFinal: true
          ),
          schemaDownloadConfiguration: .none // we always use the schema file stored in git
        ),
        withRootURL: rootURL
      )
  }
```

This will set the rootURL to the `.acropolisDirectoryURL`, but the operation input paths will still be `**/*.graphql`, so it will still pick up the operation files in each of the project subdirectories.

Using the `operationsOutputOptions: .relative(subpath: "../Sources/GraphQL/Operations", accessModifier: .public)`, the operation files will be generated relative to where the `.graphql` definition files live, so changing the `rootURL` doesn't affect those. They will still be generated into the same places in the modules that use them.

And this way, you will have _one_ generated `SchemaMetadata.swift` file with all the referenced types from all your modules in it.

2 caveats:

1. Your test support files across all the modules will be put into same folder. You could do something to move them into the right place for each module, but I actually think in most cases, it is better to have one shared TestMocks modules that you use across all your modules. Since these mocks represent the schema types, not the individual operation definition types, there would likely be a lot of duplicated code that can be shared this way.

2. If you have any cross module dependencies (like a fragment that is used by operations in multiple modules), those should be placed in the a folder that will be included in your `shared-core` module with your schema. In the future, we may consider a feature to indicate cross module dependencies and make this work otherwise.

Our [Project Configuration Guide](https://www.apollographql.com/docs/ios/project-configuration#operation-model-generation), while a bit lengthy, is a good overview of the options you have to configure the Apollo Codegen Engine to work with advanced use cases such as yours. If you have any other questions, let us know!
